// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketSystem.API.Data;

#nullable disable

namespace TicketSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306182917_UpdateSoftwareDepartmentToFullString")]
    partial class UpdateSoftwareDepartmentToFullString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TicketSystem.API.Models.AutomationTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecklistData")
                        .HasColumnType("longtext");

                    b.Property<int>("ChecklistStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProductModel")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsLineStopped")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LabelValidationType")
                        .HasColumnType("int");

                    b.Property<string>("LineCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LineStoppedTime")
                        .HasColumnType("longtext");

                    b.Property<int?>("LineSystem")
                        .HasColumnType("int");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("RequesterName")
                        .HasColumnType("longtext");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Product")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("int");

                    b.Property<string>("RunningProduct")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SystemSupportType")
                        .HasColumnType("int");

                    b.Property<string>("TargetDepartment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ResolverId")
                        .HasColumnType("int");

                    b.Property<string>("ResolverName")
                        .HasColumnType("longtext");

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.Property<int?>("ToolType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("AutomationTickets");
                });

            modelBuilder.Entity("TicketSystem.API.Models.LinePrefix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("LinePrefixes");
                });

            modelBuilder.Entity("TicketSystem.API.Models.ProductionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("LineName")
                        .IsUnique();

                    b.HasIndex("Prefix");

                    b.ToTable("ProductionLines");
                });

            modelBuilder.Entity("TicketSystem.API.Models.SetupTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("longtext");

                    b.Property<int>("ChecklistStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsLineStopped")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LineCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LineStoppedTime")
                        .HasColumnType("longtext");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("RequesterName")
                        .HasColumnType("longtext");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Product")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("int");

                    b.Property<string>("RequestedMaterial")
                        .HasColumnType("longtext");

                    b.Property<int>("SetupType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetDepartment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ResolverId")
                        .HasColumnType("int");

                    b.Property<string>("ResolverName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("SetupTickets");
                });

            modelBuilder.Entity("TicketSystem.API.Models.SoftwareTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsLineStopped")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LineStoppedTime")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("RequesterName")
                        .HasColumnType("longtext");

                    b.Property<string>("NecessaryInfo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PostLocation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Problem")
                        .HasColumnType("int");

                    b.Property<int?>("ProductionLineId")
                        .HasColumnType("int");

                    b.Property<int>("Sector")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetDepartment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ResolverId")
                        .HasColumnType("int");

                    b.Property<string>("ResolverName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("SoftwareTickets");
                });

            modelBuilder.Entity("TicketSystem.API.Models.TestTickets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChecklistStatus")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmationToken")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsLineStopped")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LineCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LineStoppedTime")
                        .HasColumnType("longtext");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<string>("RequesterName")
                        .HasColumnType("longtext");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Product")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductionLineId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TargetDepartment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ResolverId")
                        .HasColumnType("int");

                    b.Property<string>("ResolverName")
                        .HasColumnType("longtext");

                    b.Property<int>("TestType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("TestTickets");
                });

            modelBuilder.Entity("TicketSystem.API.Models.AutomationTickets", b =>
                {
                    b.HasOne("TicketSystem.API.Models.ProductionLine", "ProductionLine")
                        .WithMany("AutomationTickets")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("TicketSystem.API.Models.SetupTickets", b =>
                {
                    b.HasOne("TicketSystem.API.Models.ProductionLine", "ProductionLine")
                        .WithMany("SetupTickets")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("TicketSystem.API.Models.SoftwareTickets", b =>
                {
                    b.HasOne("TicketSystem.API.Models.ProductionLine", "ProductionLine")
                        .WithMany()
                        .HasForeignKey("ProductionLineId");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("TicketSystem.API.Models.TestTickets", b =>
                {
                    b.HasOne("TicketSystem.API.Models.ProductionLine", "ProductionLine")
                        .WithMany("TestTickets")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("TicketSystem.API.Models.ProductionLine", b =>
                {
                    b.Navigation("AutomationTickets");

                    b.Navigation("SetupTickets");

                    b.Navigation("TestTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
